/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oE3FNJgfJRWctRp1SvVjWz
// Component: DHobGCghp6tB
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Logo from "../../Logo"; // plasmic-import: Okot65MPDajf/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oE3FNJgfJRWctRp1SvVjWz/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicFooterSection.module.css"; // plasmic-import: DHobGCghp6tB/css
import TwitterIcon from "./icons/PlasmicIcon__Twitter"; // plasmic-import: bWrZnqGaAM2w/icon
import GithubIcon from "./icons/PlasmicIcon__Github"; // plasmic-import: vPOSlYWZ408-/icon
import LinkedinIcon from "./icons/PlasmicIcon__Linkedin"; // plasmic-import: NuXdjL7-tCPI/icon

createPlasmicElementProxy;

export const PlasmicFooterSection__VariantProps = new Array();

export const PlasmicFooterSection__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooterSection__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_oE3FNJgfJRWctRp1SvVjWz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames("all", sty.freeBox__sfbqq)}>
        <div className={classNames("all", sty.freeBox__i0Zzl)}>
          <Logo
            data-plasmic-name={"logo"}
            data-plasmic-override={overrides.logo}
            _50Opaque={true}
          />

          <div className={classNames("all", sty.freeBox__akLrA)}>
            <div className={classNames("all", "__wab_text", sty.text__apja3)}>
              {"Connect with us"}
            </div>
            <div className={classNames("all", sty.freeBox___6SGcT)}>
              <TwitterIcon
                className={classNames("all", sty.svg__tlt6E)}
                role={"img"}
              />

              <GithubIcon
                className={classNames("all", sty.svg__tQt3N)}
                role={"img"}
              />

              <LinkedinIcon
                className={classNames("all", sty.svg__nzLX)}
                role={"img"}
              />
            </div>
          </div>
        </div>
        <div className={classNames("all", sty.freeBox___7Mq1)}>
          <div className={classNames("all", "__wab_text", sty.text__kMaC5)}>
            {"Product"}
          </div>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__fsQKs
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Pricing"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__ecIw
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Log in"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link___67Gfc
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Integrations"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__haV2K
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Insights"}
          </PlasmicLink__>
        </div>
        <div className={classNames("all", sty.freeBox___2UrA)}>
          <div className={classNames("all", "__wab_text", sty.text__agv2U)}>
            {"Support"}
          </div>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__l3C6M
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Documentation"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__lawXc
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"FAQs"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link___4BXfl
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Status"}
          </PlasmicLink__>
        </div>
        <div className={classNames("all", sty.freeBox___6F7Gb)}>
          <div className={classNames("all", "__wab_text", sty.text__sw9Rj)}>
            {"Company"}
          </div>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__igv7W
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Contact us"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__dvtso
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Careers"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__ivOod
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"About"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__oE3FN",
              "__wab_text",
              sty.link__t4Fle
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Media"}
          </PlasmicLink__>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "logo"],
  logo: ["logo"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooterSection__ArgProps,
          internalVariantPropNames: PlasmicFooterSection__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooterSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterSection";
  } else {
    func.displayName = `PlasmicFooterSection.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterSection = Object.assign(
  // Top-level PlasmicFooterSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logo: makeNodeComponent("logo"),
    // Metadata about props expected for PlasmicFooterSection
    internalVariantProps: PlasmicFooterSection__VariantProps,
    internalArgProps: PlasmicFooterSection__ArgProps
  }
);

export default PlasmicFooterSection;
/* prettier-ignore-end */
