/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oE3FNJgfJRWctRp1SvVjWz
// Component: US579T5BNM_b
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Navbar from "../../Navbar"; // plasmic-import: na8pIlos6a3B/component
import ValueProp from "../../ValueProp"; // plasmic-import: N_Zq9mLu117T/component
import PriceCard from "../../PriceCard"; // plasmic-import: 23Jj12EtdGbx/component
import FooterSection from "../../FooterSection"; // plasmic-import: DHobGCghp6tB/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oE3FNJgfJRWctRp1SvVjWz/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicServices.module.css"; // plasmic-import: US579T5BNM_b/css
import HammerIcon from "./icons/PlasmicIcon__Hammer"; // plasmic-import: LcyOZzvDyqHj/icon
import TargetIcon from "./icons/PlasmicIcon__Target"; // plasmic-import: yepzTg4RDDiB/icon
import FastIcon from "./icons/PlasmicIcon__Fast"; // plasmic-import: hNY8Ce-ESGfA/icon
import StrongIcon from "./icons/PlasmicIcon__Strong"; // plasmic-import: 2F6GBPYD2VnS/icon
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: nd9_IlTNLsAO/icon

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    title: "Services",
    openGraph: {
      title: "Services"
    },
    twitter: {
      card: "summary",
      title: "Services"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicServices__VariantProps = new Array();

export const PlasmicServices__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicServices__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_oE3FNJgfJRWctRp1SvVjWz",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <div className={classNames("all", sty.freeBox__goZwc)}>
            <div
              data-plasmic-name={"foreground"}
              data-plasmic-override={overrides.foreground}
              className={classNames("all", sty.foreground)}
            >
              <div
                className={classNames("all", "__wab_text", sty.text___8ScGt)}
              >
                {"Our services"}
              </div>
              <div className={classNames("all", "__wab_text", sty.text__mtw3S)}>
                {
                  "A euismod eros a hendrerit tristique suscipit sit aptent dolor adipiscing inceptos cras ullamcorper a vivamus parturient."
                }
              </div>
            </div>
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames("all", sty.foreground2)}
            >
              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp___9N58C)}
                description={
                  "Quis iaculis tempor a condimentum per eu montes quis inceptos mi et dis suspendisse integer dui. Orci ad pharetra a vestibulum parturient mauris ac nisl cursus at a vestibulum morbi conubia suspendisse massa vestibulum a varius."
                }
                icon={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mChBy)}
                    displayHeight={"56px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"56px"}
                    src={{
                      src: "/plasmic/landing_page_starter/images/chart.png",
                      fullWidth: 144,
                      fullHeight: 144,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={"Accomplish more"}
              />

              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp__knQdt)}
                description={
                  "Ut interdum consectetur a interdum parturient blandit vestibulum vel quisque quis lorem libero imperdiet a sed massa quisque rhoncus sed cum quisque morbi."
                }
                icon={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__sjdaw)}
                    displayHeight={"56px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"56px"}
                    src={{
                      src: "/plasmic/landing_page_starter/images/sparkle.png",
                      fullWidth: 144,
                      fullHeight: 144,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={"Best-in-class"}
              />

              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp__doSc5)}
                description={
                  "Ullamcorper adipiscing adipiscing euismod odio nascetur eu magnis pretium arcu fermentum a eget cubilia tempor. Eu cubilia sodales vestibulum massa non ipsum consectetur lorem nibh parturient parturient vestibulum cum cras penatibus donec dui sit sed eleifend conubia condimentum parturient rutrum."
                }
                icon={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dfp9O)}
                    displayHeight={"56px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"56px"}
                    src={{
                      src: "/plasmic/landing_page_starter/images/medal.png",
                      fullWidth: 144,
                      fullHeight: 144,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={"Championship award-winners"}
              />

              <ValueProp
                card={true}
                className={classNames("__wab_instance", sty.valueProp__kuS8P)}
                description={
                  "Est parturient imperdiet proin inceptos parturient dignissim risus auctor cubilia cum iaculis eu feugiat justo eu vel at non nisl laoreet ligula porttitor a nunc ac cum habitant urna."
                }
                icon={
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5Gvel)}
                    displayHeight={"56px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"56px"}
                    src={{
                      src: "/plasmic/landing_page_starter/images/trophy.png",
                      fullWidth: 144,
                      fullHeight: 144,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={"Destined for greatness"}
              />
            </div>
          </div>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames("all", sty.section)}
          >
            <div
              data-plasmic-name={"foreground3"}
              data-plasmic-override={overrides.foreground3}
              className={classNames("all", sty.foreground3)}
            >
              <div className={classNames("all", sty.freeBox___2Jw5Z)}>
                <div className={classNames("all", sty.freeBox__zMvSv)}>
                  <h2
                    data-plasmic-name={"h2"}
                    data-plasmic-override={overrides.h2}
                    className={classNames(
                      "all",
                      "h2",
                      "h2__oE3FN",
                      "__wab_text",
                      sty.h2
                    )}
                  >
                    {"Next-level"}
                  </h2>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__bbYp7)}
                >
                  {"Dui urna enim a tempus commodo adipiscing ullamcorper."}
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__pBfj6)}>
                <div
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  className={classNames("all", sty.columns)}
                >
                  <div className={classNames("all", sty.column__nQteM)}>
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp___771La
                      )}
                      darkBackground={true}
                      description={
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__einFm
                          )}
                        >
                          {
                            "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                          }
                        </div>
                      }
                      icon={
                        <HammerIcon
                          className={classNames("all", sty.svg__z4Jj4)}
                          role={"img"}
                        />
                      }
                      title={"Harder"}
                      vertical={true}
                    />
                  </div>
                  <div className={classNames("all", sty.column__i32UB)}>
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp__qqcmC
                      )}
                      darkBackground={true}
                      description={
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__fGsZh
                          )}
                        >
                          {
                            "Consequat scelerisque a eros taciti nisl a sodales."
                          }
                        </div>
                      }
                      icon={
                        <TargetIcon
                          className={classNames("all", sty.svg__zU3E)}
                          role={"img"}
                        />
                      }
                      title={"Better"}
                      vertical={true}
                    />
                  </div>
                  <div className={classNames("all", sty.column__t7Gag)}>
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp___80Zfx
                      )}
                      darkBackground={true}
                      description={
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__rqYar
                          )}
                        >
                          {
                            "Varius ad malesuada ullamcorper cursus scelerisque a a."
                          }
                        </div>
                      }
                      icon={
                        <FastIcon
                          className={classNames("all", sty.svg__n2QEc)}
                          role={"img"}
                        />
                      }
                      title={"Faster"}
                      vertical={true}
                    />
                  </div>
                  <div className={classNames("all", sty.column__uJfDy)}>
                    <ValueProp
                      className={classNames(
                        "__wab_instance",
                        sty.valueProp___48Dou
                      )}
                      darkBackground={true}
                      description={
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__fEw3Z
                          )}
                        >
                          {
                            "Ut eu nam nostra taciti congue adipiscing curabitur."
                          }
                        </div>
                      }
                      icon={
                        <StrongIcon
                          className={classNames("all", sty.svg__seLpl)}
                          role={"img"}
                        />
                      }
                      title={"Stronger"}
                      vertical={true}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>
          <div className={classNames("all", sty.freeBox___1UsEy)}>
            <div className={classNames("all", sty.freeBox__wS9Xl)}>
              <div className={classNames("all", sty.freeBox__ndOfk)}>
                <div className={classNames("all", sty.freeBox__fmbMi)}>
                  <div
                    className={classNames("all", "__wab_text", sty.text__b5JiI)}
                  >
                    {"Pricing plans"}
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__zcxlu)}
                >
                  {
                    "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                  }
                </div>
              </div>
              <div className={classNames("all", sty.freeBox__mnbmt)}>
                <PriceCard
                  className={classNames("__wab_instance", sty.priceCard__eouQn)}
                  description={
                    <React.Fragment>
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__raj8S
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__cpPd6)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__n3Yd
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__crvZ)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />
                    </React.Fragment>
                  }
                  dollars={"0"}
                />

                <PriceCard
                  className={classNames(
                    "__wab_instance",
                    sty.priceCard___0Lbkz
                  )}
                  description={
                    <React.Fragment>
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__ssw5D
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__vZxQs)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__jrZdA
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__kntx7)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__u2I6W
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__mgE7J)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />
                    </React.Fragment>
                  }
                  dollars={"8"}
                  label={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__pk79X
                      )}
                    >
                      {"Pro"}
                    </div>
                  }
                />

                <PriceCard
                  className={classNames("__wab_instance", sty.priceCard__xmiqw)}
                  description={
                    <React.Fragment>
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp___16N1L
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__ylIso)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp___7IndU
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__nwWyE)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__zBstT
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__iYAo)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp___3Dxb
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg___4Myi)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />
                    </React.Fragment>
                  }
                  dollars={"16"}
                  label={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__vtD65
                      )}
                    >
                      {"Team"}
                    </div>
                  }
                />

                <PriceCard
                  className={classNames("__wab_instance", sty.priceCard__m0Ew0)}
                  description={
                    <React.Fragment>
                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__yrP1H
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__guXd)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__eYwaA
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__zkjMz)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__w46K
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__bzR2)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />

                      <ValueProp
                        className={classNames(
                          "__wab_instance",
                          sty.valueProp__med1
                        )}
                        description={"Nulla odio mauris."}
                        flatIcon={true}
                        icon={
                          <CheckIcon
                            className={classNames("all", sty.svg__qcmr)}
                            role={"img"}
                          />
                        }
                        noTitle={true}
                      />
                    </React.Fragment>
                  }
                  dollars={"?"}
                  label={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__bv6Ss
                      )}
                    >
                      {"Enterprise"}
                    </div>
                  }
                  primary={true}
                />
              </div>
            </div>
          </div>
          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "foreground",
    "foreground2",
    "section",
    "foreground3",
    "h2",
    "columns",
    "footerSection"
  ],

  navbar: ["navbar"],
  foreground: ["foreground"],
  foreground2: ["foreground2"],
  section: ["section", "foreground3", "h2", "columns"],
  foreground3: ["foreground3", "h2", "columns"],
  h2: ["h2"],
  columns: ["columns"],
  footerSection: ["footerSection"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicServices__ArgProps,
          internalVariantPropNames: PlasmicServices__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    foreground: makeNodeComponent("foreground"),
    foreground2: makeNodeComponent("foreground2"),
    section: makeNodeComponent("section"),
    foreground3: makeNodeComponent("foreground3"),
    h2: makeNodeComponent("h2"),
    columns: makeNodeComponent("columns"),
    footerSection: makeNodeComponent("footerSection"),
    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/services",
      pagePath: "/services",
      params: {},
      query: {}
    })
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
