/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oE3FNJgfJRWctRp1SvVjWz
// Component: WDH2fCrqGWz-
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import { unstable_usePlasmicQueries } from "@plasmicapp/react-web/lib/data-sources";
import Navbar from "../../Navbar"; // plasmic-import: na8pIlos6a3B/component
import ValueProp from "../../ValueProp"; // plasmic-import: N_Zq9mLu117T/component
import Section from "../../Section"; // plasmic-import: 0OUkU0_5vn08/component
import { CmsQueryRepeater } from "@plasmicpkgs/plasmic-cms";
import { CmsRowField } from "@plasmicpkgs/plasmic-cms";
import ListItem from "../../ListItem"; // plasmic-import: WT98o2qUzdn3/component
import PriceCard from "../../PriceCard"; // plasmic-import: 23Jj12EtdGbx/component
import Banner from "../../Banner"; // plasmic-import: KTSy7T7OaxXU/component
import Testimonial from "../../Testimonial"; // plasmic-import: SNhJ45SfzeB3/component
import CallToActionSection from "../../CallToActionSection"; // plasmic-import: yeouuV7SEEIK/component
import FooterSection from "../../FooterSection"; // plasmic-import: DHobGCghp6tB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oE3FNJgfJRWctRp1SvVjWz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oE3FNJgfJRWctRp1SvVjWz/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: WDH2fCrqGWz-/css
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: nd9_IlTNLsAO/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: 2d_T1ryx2jEa/icon
import CheckCircleIcon from "./icons/PlasmicIcon__CheckCircle"; // plasmic-import: JLREm-YHtuao/icon
import { fetchTables as __fn_plasmicCms__fetchTables } from "@plasmicpkgs/cms";
import { fetchContent as __fn_plasmicCms__fetchContent } from "@plasmicpkgs/cms";

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    title: "Home",
    openGraph: {
      title: "Home"
    },
    twitter: {
      card: "summary",
      title: "Home"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {
  plasmicCms: {
    fetchTables: __fn_plasmicCms__fetchTables,
    fetchContent: __fn_plasmicCms__fetchContent
  }
};

export const serverQueryTree = {
  type: "component",
  queries: {
    query: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        { host: "https://data.plasmic.app" }
      ]
    },
    query2: {
      id: "plasmicCms.fetchTables",
      fn: $$.plasmicCms.fetchTables,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsId: null,
            cmsPublicToken: null
          };
          __composite["cmsId"] = "mv5gk75b42rXk6fddUdQhx";
          __composite["cmsPublicToken"] =
            "5BvmXVOgbITAtxDf2WvTu4U5AqIyGIDHgHYyMOkolLxPdn92VtYOlzamdtwBMbcwnm0wqy23FAzZWtbqkA";
          return __composite;
        })()
      ]
    },
    query3: {
      id: "plasmicCms.fetchTables",
      fn: $$.plasmicCms.fetchTables,
      args: ({ $q, $props, $ctx, $state }) => [
        { host: "https://data.plasmic.app" }
      ]
    },
    query4: {
      id: "plasmicCms.fetchTables",
      fn: $$.plasmicCms.fetchTables,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsPublicToken: null,
            cmsId: null
          };
          __composite["cmsPublicToken"] =
            "5BvmXVOgbITAtxDf2WvTu4U5AqIyGIDHgHYyMOkolLxPdn92VtYOlzamdtwBMbcwnm0wqy23FAzZWtbqkA";
          __composite["cmsId"] = "mv5gk75b42rXk6fddUdQhx";
          return __composite;
        })()
      ]
    },
    query5: {
      id: "plasmicCms.fetchTables",
      fn: $$.plasmicCms.fetchTables,
      args: ({ $q, $props, $ctx, $state }) => [
        { host: "https://data.plasmic.app" }
      ]
    }
  },
  propsContext: {},
  stateSpecs: [],
  children: []
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const $q = unstable_usePlasmicQueries(serverQueryTree, $ctx, $props, null);
  const globalVariants = _useGlobalVariants();
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy($q),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_oE3FNJgfJRWctRp1SvVjWz",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"headerHeroSection"}
            data-plasmic-override={overrides.headerHeroSection}
            className={classNames("all", sty.headerHeroSection)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div className={classNames("all", sty.columns__a1Wr)}>
              <div className={classNames("all", sty.column__fj9Mm)}>
                <div className={classNames("all", sty.freeBox__jzajF)}>
                  <div className={classNames("all", sty.freeBox__pGfQ4)}>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__wSVf
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Vito"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span plasmic_default__span__oE3FN"
                          }
                          style={{ color: "#1E5FCE" }}
                        >
                          {"IT"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__kS5SU
                      )}
                    >
                      {
                        "Professional IT Field Services \u2014 Network infrastructure, hardware deployment, and enterprise support across the US."
                      }
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames("all", sty.column__fRdHu)}>
                <div className={classNames("all", sty.freeBox__ifxBf)}>
                  <ValueProp
                    card={true}
                    className={classNames(
                      "__wab_instance",
                      sty.valueProp__v8Ulr
                    )}
                    description={
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__ea3G
                        )}
                      >
                        {"Sherborn, MA, US\n"}
                      </div>
                    }
                    icon={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__fSaXv)}
                        displayHeight={"56px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={
                          "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/red-apple_1f34e.png"
                        }
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__musIo
                        )}
                      >
                        {"Location"}
                      </div>
                    }
                  />

                  <ValueProp
                    card={true}
                    className={classNames(
                      "__wab_instance",
                      sty.valueProp__fPwkK
                    )}
                    description={
                      <PlasmicLink__
                        className={classNames(
                          "all",
                          "a",
                          "a__oE3FN",
                          "__wab_text",
                          sty.link__rCFd
                        )}
                        component={Link}
                        href={"tel:7742443563"}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"(774) 244-3563"}
                      </PlasmicLink__>
                    }
                    icon={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hkojG)}
                        displayHeight={"56px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"56px"}
                        src={
                          "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/red-apple_1f34e.png"
                        }
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text___7R4PL
                        )}
                      >
                        {"Phone"}
                      </div>
                    }
                  />

                  <ValueProp
                    card={true}
                    className={classNames(
                      "__wab_instance",
                      sty.valueProp__evWo8
                    )}
                    description={
                      <React.Fragment>
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__kIZnH
                          )}
                        >
                          {""}
                        </div>
                        <PlasmicLink__
                          className={classNames(
                            "all",
                            "a",
                            "a__oE3FN",
                            "__wab_text",
                            sty.link__cr566
                          )}
                          component={Link}
                          href={"mailto:Vitoit@protonmail.com"}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          {"Vitoit@protonmail.com"}
                        </PlasmicLink__>
                      </React.Fragment>
                    }
                    icon={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__xmkcz)}
                        displayHeight={"56px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"56px"}
                        src={
                          "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/red-apple_1f34e.png"
                        }
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text___6XwEb
                        )}
                      >
                        {"Phone"}
                      </div>
                    }
                  />
                </div>
              </div>
            </div>
          </div>
          <Section
            data-plasmic-name={"valuePropsSection"}
            data-plasmic-override={overrides.valuePropsSection}
            background={"_new"}
            className={classNames("__wab_instance", sty.valuePropsSection)}
          >
            <h3
              data-plasmic-name={"h3"}
              data-plasmic-override={overrides.h3}
              className={classNames(
                "all",
                "h3",
                "h3__oE3FN",
                "__wab_text",
                sty.h3
              )}
              id={"services_section"}
            >
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__oE3FN"
                  }
                  style={{ color: "var(--token-G8D0FNZg11er)" }}
                >
                  {"Services"}
                </span>
              </React.Fragment>
            </h3>
            <div className={classNames("all", sty.freeBox__mHvVb)}>
              <div className={classNames("all", sty.freeBox__fYtwJ)}>
                <ValueProp
                  card={true}
                  className={classNames("__wab_instance", sty.valueProp__fPOif)}
                  description={""}
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__kzdm1)}
                      role={"img"}
                    />
                  }
                  title={"Small Business Network Install"}
                />

                <ValueProp
                  card={true}
                  className={classNames("__wab_instance", sty.valueProp__bYNnG)}
                  description={""}
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__smlQy)}
                      role={"img"}
                    />
                  }
                  title={"Smart House Implementation"}
                />

                <ValueProp
                  card={true}
                  className={classNames("__wab_instance", sty.valueProp__iHpWx)}
                  description={""}
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__vWrCk)}
                      role={"img"}
                    />
                  }
                  title={"IT Projects"}
                />
              </div>
            </div>
          </Section>
          <div className={classNames("all", sty.freeBox___3L5Wy)}>
            <CmsQueryRepeater
              data-plasmic-name={"cmsDataFetcher"}
              data-plasmic-override={overrides.cmsDataFetcher}
              className={classNames("__wab_instance", sty.cmsDataFetcher)}
              desc={false}
              emptyMessage={
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__igVtO
                      )}
                    >
                      {"No matching published entries found."}
                    </div>
                  )}
                </DataCtxReader__>
              }
              forceEmptyState={false}
              forceLoadingState={false}
              limit={0}
              loadingMessage={
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__hfp2S
                      )}
                    >
                      {"Loading..."}
                    </div>
                  )}
                </DataCtxReader__>
              }
              noAutoRepeat={false}
              noLayout={false}
              table={"newModel"}
              useDraft={false}
            >
              <DataCtxReader__>
                {$ctx => (
                  <div className={classNames("all", sty.freeBox__miNVv)}>
                    <CmsRowField
                      data-plasmic-name={"cmsEntryField"}
                      data-plasmic-override={overrides.cmsEntryField}
                      className={classNames(
                        "__wab_instance",
                        sty.cmsEntryField
                      )}
                      themeResetClassName={classNames(
                        "root_reset_oE3FNJgfJRWctRp1SvVjWz",
                        "root_reset_oE3FNJgfJRWctRp1SvVjWz_tags",
                        "plasmic_default_styles",
                        "plasmic_mixins",
                        styleTokensClassNames
                      )}
                    />
                  </div>
                )}
              </DataCtxReader__>
            </CmsQueryRepeater>
          </div>
          <Section
            data-plasmic-name={"checkpointsSection"}
            data-plasmic-override={overrides.checkpointsSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.checkpointsSection)}
          >
            <div
              className={classNames("all", sty.columns__rE9Qy)}
              id={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "features"
                  : "features"
              }
            >
              <div className={classNames("all", sty.column__eCwgH)}>
                <div className={classNames("all", sty.freeBox__yRosW)}>
                  <div
                    className={classNames("all", "__wab_text", sty.text__x8JNk)}
                  >
                    {"Freedoms"}
                  </div>
                  <h2
                    data-plasmic-name={"h2"}
                    data-plasmic-override={overrides.h2}
                    className={classNames(
                      "all",
                      "h2",
                      "h2__oE3FN",
                      "__wab_text",
                      sty.h2
                    )}
                  >
                    {"Open by design"}
                  </h2>
                  <div
                    className={classNames("all", "__wab_text", sty.text__qcajm)}
                  >
                    {
                      "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                    }
                  </div>
                  <div className={classNames("all", sty.freeBox__ppwm5)}>
                    <PlasmicLink__
                      className={classNames(
                        "all",
                        "a",
                        "a__oE3FN",
                        "__wab_text",
                        sty.link__bjmur
                      )}
                      component={Link}
                      href={"https://www.plasmic.app/"}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Learn more"}
                    </PlasmicLink__>
                    <ChevronRightIcon
                      className={classNames("all", sty.svg__aoyoZ)}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>
              <div className={classNames("all", sty.column__wQ0Yz)}>
                <div className={classNames("all", sty.freeBox___6WXjj)}>
                  <ListItem
                    bottomBorder={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "dark"
                        : "dark"
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__dm6Ea
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__rEfcc)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__pf0VP
                      )}
                    >
                      {"Built on capability"}
                    </div>
                  </ListItem>
                  <ListItem
                    bottomBorder={"dark"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__gVtfD
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__vnag3)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__ubtqO
                      )}
                    >
                      {"Highly energetic"}
                    </div>
                  </ListItem>
                  <ListItem
                    bottomBorder={"dark"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__ln9M6
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg___1YQ6C)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__aegHf
                      )}
                    >
                      {"100% transparency and accountability"}
                    </div>
                  </ListItem>
                  <ListItem
                    bottomBorder={"dark"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__tmKpL
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__b4LH)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__gbbzt
                      )}
                    >
                      {"Refreshing clarity"}
                    </div>
                  </ListItem>
                  <ListItem
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__plW8K
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__iqcMb)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__v0Ftx
                      )}
                    >
                      {"Modern results"}
                    </div>
                  </ListItem>
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"pricingSection"}
            data-plasmic-override={overrides.pricingSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.pricingSection)}
          >
            <div className={classNames("all", sty.freeBox__h40Vq)}>
              <div className={classNames("all", sty.freeBox__vsOr)}>
                <div className={classNames("all", sty.freeBox__pNFcp)} />
                <div
                  className={classNames("all", "__wab_text", sty.text__i4NJu)}
                >
                  {
                    "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                  }
                </div>
              </div>
              <div className={classNames("all", sty.columns__srHi)}>
                <div className={classNames("all", sty.column__qkIho)}>
                  <PriceCard
                    borders={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? []
                        : ["flatRight"]
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__mQwZa
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___7DaEs
                          )}
                          description={
                            "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__g8FJ)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___54F5
                          )}
                          description={"Mus consequat a justo"}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__yaBZl)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                  />
                </div>
                <div className={classNames("all", sty.column__nwYn6)}>
                  <PriceCard
                    borders={[]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__pqkQv
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__eywlK
                          )}
                          description={
                            "Ligula primis mollis sem dignissim semper lectus parturient"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__ifShM)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__k2Axx
                          )}
                          description={
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__po0IL
                              )}
                            >
                              {"A curabitur dignissim pharetra porta suscipit"}
                            </div>
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__rd9Oy)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__cWw1J
                          )}
                          description={
                            "Condimentum diam a et sapien praesent potenti torquent a eros"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__no1Eo)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___7Iepu
                          )}
                          description={
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__mflZ
                              )}
                            >
                              {"Conubia in hac eu elementum sodales"}
                            </div>
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__mxkJa)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"16"}
                    label={"PRO"}
                    primary={true}
                  />
                </div>
                <div className={classNames("all", sty.column__biKwj)}>
                  <PriceCard
                    borders={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? []
                        : ["flatLeft"]
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__eM6Pd
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__tRqk
                          )}
                          description={"Ad nam curae a potenti platea"}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__vav1Q)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__njZ8
                          )}
                          description={
                            "A adipiscing scelerisque pretium consectetur sem"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__zwWz9)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"10"}
                    label={"Team"}
                  />
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"shopBannersSection"}
            data-plasmic-override={overrides.shopBannersSection}
            className={classNames("__wab_instance", sty.shopBannersSection)}
            size={"fullContentWidth"}
          >
            <div className={classNames("all", sty.freeBox___3QoFj)}>
              <Banner
                className={classNames("__wab_instance", sty.banner__doYsY)}
                image={{
                  src: "/plasmic/landing_page_starter/images/sunglassesMale.jpg",
                  fullWidth: 2851,
                  fullHeight: 1900,
                  aspectRatio: undefined
                }}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text___5W20G
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__aZSaQ
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>
                    <div className={classNames("all", sty.freeBox___0Mf6P)}>
                      <PlasmicLink__
                        className={classNames(
                          "all",
                          "a",
                          "a__oE3FN",
                          "__wab_text",
                          sty.link__cgAno
                        )}
                        component={Link}
                        href={"#"}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Go to collection"}
                      </PlasmicLink__>
                      <ChevronRightIcon
                        className={classNames("all", sty.svg__s6WyE)}
                        role={"img"}
                      />
                    </div>
                  </React.Fragment>
                }
              />

              <div className={classNames("all", sty.freeBox__j5Iv5)}>
                <Banner
                  className={classNames("__wab_instance", sty.banner__bQlz8)}
                  image={{
                    src: "/plasmic/landing_page_starter/images/sneakers.jpg",
                    fullWidth: 2850,
                    fullHeight: 1900,
                    aspectRatio: undefined
                  }}
                  left={
                    <React.Fragment>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__fLdu
                        )}
                      >
                        {"Sneakers\nCollection"}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__lyN3X
                        )}
                      >
                        {"Get 25% off on selected items"}
                      </div>
                      <div className={classNames("all", sty.freeBox__xiKl4)}>
                        <PlasmicLink__
                          className={classNames(
                            "all",
                            "a",
                            "a__oE3FN",
                            "__wab_text",
                            sty.link__v7ED
                          )}
                          component={Link}
                          href={"#"}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          {"Go to collection"}
                        </PlasmicLink__>
                        <ChevronRightIcon
                          className={classNames("all", sty.svg___3E9B0)}
                          role={"img"}
                        />
                      </div>
                    </React.Fragment>
                  }
                />

                <Banner
                  className={classNames("__wab_instance", sty.banner__yxz7G)}
                  image={{
                    src: "/plasmic/landing_page_starter/images/shirtWoman.png",
                    fullWidth: 1834,
                    fullHeight: 2751,
                    aspectRatio: undefined
                  }}
                  left={
                    <React.Fragment>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__c50V
                        )}
                      >
                        {"Shirts\nCollection"}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__w9Vdt
                        )}
                      >
                        {"Get 25% off on selected items"}
                      </div>
                      <div className={classNames("all", sty.freeBox__lfq0Q)}>
                        <PlasmicLink__
                          className={classNames(
                            "all",
                            "a",
                            "a__oE3FN",
                            "__wab_text",
                            sty.link__o2YOr
                          )}
                          component={Link}
                          href={"#"}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          {"Go to collection"}
                        </PlasmicLink__>
                        <ChevronRightIcon
                          className={classNames("all", sty.svg___2UaZj)}
                          role={"img"}
                        />
                      </div>
                    </React.Fragment>
                  }
                />
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"logoCloudSection"}
            data-plasmic-override={overrides.logoCloudSection}
            className={classNames("__wab_instance", sty.logoCloudSection)}
          >
            <div className={classNames("all", sty.freeBox___9OeZq)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___3BdT)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/loom.svg",
                  fullWidth: 300,
                  fullHeight: 91,
                  aspectRatio: 3.303226
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__tlxN1)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/strapi.svg",
                  fullWidth: 300,
                  fullHeight: 78,
                  aspectRatio: 3.849624
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__cQ7B)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/segment.svg",
                  fullWidth: 300,
                  fullHeight: 62,
                  aspectRatio: 4.87619
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__aU8Kh)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/xstate.svg",
                  fullWidth: 300,
                  fullHeight: 94,
                  aspectRatio: 3.2
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__aQ4A)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/mapbox.svg",
                  fullWidth: 300,
                  fullHeight: 67,
                  aspectRatio: 4.491228
                }}
              />
            </div>
          </Section>
          <Section
            data-plasmic-name={"testimonialsSection"}
            data-plasmic-override={overrides.testimonialsSection}
            background={"gray"}
            className={classNames("__wab_instance", sty.testimonialsSection)}
          >
            <div className={classNames("all", sty.columns__f2VQ1)}>
              <div className={classNames("all", sty.column__o7Shc)}>
                <Testimonial
                  className={classNames(
                    "__wab_instance",
                    sty.testimonial__eWxMe
                  )}
                  image={{
                    src: "/plasmic/landing_page_starter/images/tracy.png",
                    fullWidth: 500,
                    fullHeight: 500,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames("all", sty.column__blpBb)}>
                <Testimonial
                  className={classNames(
                    "__wab_instance",
                    sty.testimonial__aOdMi
                  )}
                  image={{
                    src: "/plasmic/landing_page_starter/images/elaine.png",
                    fullWidth: 460,
                    fullHeight: 280,
                    aspectRatio: undefined
                  }}
                  name={"Elaine Benes"}
                  quote={
                    <React.Fragment>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__iz0Hv
                        )}
                      >
                        {'"Vestibulum lacinia varius habitant dis aenean.'}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__hiwQt
                        )}
                      >
                        {
                          'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                        }
                      </div>
                    </React.Fragment>
                  }
                  title={"Editor, Pendant Publishing"}
                />
              </div>
              <div className={classNames("all", sty.column__tlwRr)}>
                <Testimonial
                  className={classNames(
                    "__wab_instance",
                    sty.testimonial__g2AkY
                  )}
                  image={{
                    src: "/plasmic/landing_page_starter/images/louis.jpg",
                    fullWidth: 2249,
                    fullHeight: 3000,
                    aspectRatio: undefined
                  }}
                  name={"Louis Huang"}
                  quote={
                    '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
                  }
                  title={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__jtbFy
                      )}
                    >
                      {"Restaurant Owner, Cattleman's Ranch"}
                    </div>
                  }
                />
              </div>
            </div>
          </Section>
          <CallToActionSection
            data-plasmic-name={"callToActionSection"}
            data-plasmic-override={overrides.callToActionSection}
            className={classNames("__wab_instance", sty.callToActionSection)}
            image={{
              src: "/plasmic/landing_page_starter/images/meeting.jpg",
              fullWidth: 2916,
              fullHeight: 1787,
              aspectRatio: undefined
            }}
          />

          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />

          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
          ) ? (
            <div className={classNames("all", "__wab_text", sty.text__jGrPx)}>
              {"414px"}
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "valuePropsSection",
    "h3",
    "cmsDataFetcher",
    "cmsEntryField",
    "checkpointsSection",
    "h2",
    "pricingSection",
    "shopBannersSection",
    "logoCloudSection",
    "testimonialsSection",
    "callToActionSection",
    "footerSection"
  ],

  headerHeroSection: ["headerHeroSection", "navbar"],
  navbar: ["navbar"],
  valuePropsSection: ["valuePropsSection", "h3"],
  h3: ["h3"],
  cmsDataFetcher: ["cmsDataFetcher", "cmsEntryField"],
  cmsEntryField: ["cmsEntryField"],
  checkpointsSection: ["checkpointsSection", "h2"],
  h2: ["h2"],
  pricingSection: ["pricingSection"],
  shopBannersSection: ["shopBannersSection"],
  logoCloudSection: ["logoCloudSection"],
  testimonialsSection: ["testimonialsSection"],
  callToActionSection: ["callToActionSection"],
  footerSection: ["footerSection"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    valuePropsSection: makeNodeComponent("valuePropsSection"),
    h3: makeNodeComponent("h3"),
    cmsDataFetcher: makeNodeComponent("cmsDataFetcher"),
    cmsEntryField: makeNodeComponent("cmsEntryField"),
    checkpointsSection: makeNodeComponent("checkpointsSection"),
    h2: makeNodeComponent("h2"),
    pricingSection: makeNodeComponent("pricingSection"),
    shopBannersSection: makeNodeComponent("shopBannersSection"),
    logoCloudSection: makeNodeComponent("logoCloudSection"),
    testimonialsSection: makeNodeComponent("testimonialsSection"),
    callToActionSection: makeNodeComponent("callToActionSection"),
    footerSection: makeNodeComponent("footerSection"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
