/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oE3FNJgfJRWctRp1SvVjWz
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsp9IitOuGb6S } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: p9iit_OuGb6s/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsp9IitOuGb6S
});
