/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oE3FNJgfJRWctRp1SvVjWz
// Component: LZEtyTk876xa
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Button from "../../Button"; // plasmic-import: hWiarQquCkSU/component
import Divider from "../../Divider"; // plasmic-import: lWWgXZMlHqKr/component
import TextField from "../../TextField"; // plasmic-import: -bjKjCKStmMX/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: oE3FNJgfJRWctRp1SvVjWz/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicSignUpPrompt.module.css"; // plasmic-import: LZEtyTk876xa/css
import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: VHtbySoK2oHo/icon
import GoogleIcon from "./icons/PlasmicIcon__Google"; // plasmic-import: HD3TLTeOqPd7/icon

createPlasmicElementProxy;

export const PlasmicSignUpPrompt__VariantProps = new Array();

export const PlasmicSignUpPrompt__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSignUpPrompt__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "name.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "email.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "password.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_oE3FNJgfJRWctRp1SvVjWz",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames("all", sty.freeBox__rPiZm)}>
        <div className={classNames("all", sty.freeBox__zrGr4)}>
          <div className={classNames("all", "__wab_text", sty.text__yLb0C)}>
            {"Sign up with"}
          </div>
          <div className={classNames("all", sty.freeBox__lQwUp)}>
            <Button
              className={classNames("__wab_instance", sty.button__ihqfy)}
              color={"neutral"}
              iconStart={true}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text___6JcGw)}
                >
                  {"Apple"}
                </div>
              }
              start={
                <AppleIcon
                  className={classNames("all", sty.svg__gwfMh)}
                  role={"img"}
                />
              }
              submitsForm={true}
              type={"bordered"}
            />

            <Button
              className={classNames("__wab_instance", sty.button__xgWuJ)}
              color={"neutral"}
              iconStart={true}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__qjrZs)}
                >
                  {"Google"}
                </div>
              }
              start={
                <GoogleIcon
                  className={classNames("all", sty.svg__sb23F)}
                  role={"img"}
                />
              }
              submitsForm={true}
              type={"bordered"}
            />
          </div>
          <div className={classNames("all", sty.freeBox__pCg4L)}>
            <Divider
              className={classNames("__wab_instance", sty.divider__b98NI)}
            />

            <div className={classNames("all", "__wab_text", sty.text__jQy98)}>
              {"Or"}
            </div>
            <Divider
              className={classNames("__wab_instance", sty.divider__ubMgz)}
            />
          </div>
          <div className={classNames("all", sty.freeBox__x3Cjz)}>
            <TextField
              data-plasmic-name={"name"}
              data-plasmic-override={overrides.name}
              className={classNames("__wab_instance", sty.name)}
              inputMode={"text"}
              onChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, ["name", "value"]).apply(
                  null,
                  eventArgs
                );
                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Full Name"}
              showLabel={false}
              type={"text"}
            />

            <TextField
              data-plasmic-name={"email"}
              data-plasmic-override={overrides.email}
              className={classNames("__wab_instance", sty.email)}
              inputMode={"email"}
              onChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, ["email", "value"]).apply(
                  null,
                  eventArgs
                );
                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Email"}
              showLabel={false}
              type={"email"}
            />

            <TextField
              data-plasmic-name={"password"}
              data-plasmic-override={overrides.password}
              className={classNames("__wab_instance", sty.password)}
              onChange={async (...eventArgs) => {
                generateStateOnChangeProp($state, ["password", "value"]).apply(
                  null,
                  eventArgs
                );
                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Password"}
              showLabel={false}
              type={"password"}
            />

            <Button
              className={classNames("__wab_instance", sty.button__xIwqb)}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__lz0Jx)}
                >
                  {"Start your account"}
                </div>
              }
              size={"extraLarge"}
              submitsForm={true}
            />
          </div>
        </div>
        <Divider className={classNames("__wab_instance", sty.divider__dHbZb)} />
        <div className={classNames("all", sty.freeBox__wwnF)}>
          <div className={classNames("all", "__wab_text", sty.text__kWsPf)}>
            {
              "A cras sagittis odio vestibulum pulvinar a eget hendrerit id vestibulum a leo sociosqu dictumst dictumst natoque magnis parturient."
            }
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "name", "email", "password"],
  name: ["name"],
  email: ["email"],
  password: ["password"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignUpPrompt__ArgProps,
          internalVariantPropNames: PlasmicSignUpPrompt__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignUpPrompt__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignUpPrompt";
  } else {
    func.displayName = `PlasmicSignUpPrompt.${nodeName}`;
  }
  return func;
}

export const PlasmicSignUpPrompt = Object.assign(
  // Top-level PlasmicSignUpPrompt renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    _name: makeNodeComponent("name"),
    email: makeNodeComponent("email"),
    password: makeNodeComponent("password"),
    // Metadata about props expected for PlasmicSignUpPrompt
    internalVariantProps: PlasmicSignUpPrompt__VariantProps,
    internalArgProps: PlasmicSignUpPrompt__ArgProps
  }
);

export default PlasmicSignUpPrompt;
/* prettier-ignore-end */
