/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oE3FNJgfJRWctRp1SvVjWz
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: oE3FNJgfJRWctRp1SvVjWz/projectModule

const data = {
  base: `${"plasmic_tokens_oE3FNJgfJRWctRp1SvVjWz"} ${"plasmic_tokens_ohDidvG9XsCeFumugENU3J"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
